## **DECISION TREE**

***About Dataset:**
The "Baseball Player Metrics" dataset comprises comprehensive statistical records for a diverse range of baseball players. It encompasses essential performance metrics such as games played, at-bats, runs scored, hits, doubles, triples, home runs, and runs batted in (RBI) for each player. With data spanning multiple years and including unique players, this dataset offers insights into individual player performance and allows for comparative analyses across different eras and player styles. Researchers, analysts, and enthusiasts can utilize this dataset to explore trends, assess player contributions, and gain a deeper understanding of the dynamics of baseball over time. Whether studying the evolution of the game or evaluating the impact of specific players, this dataset serves as a valuable resource for baseball-related analysis and research endeavors.*

*Player: The name of the baseball player.
YRS: The number of years the player has been active in professional baseball.
G: The total number of games played by the player.
AB: The total number of at-bats (plate appearances) by the player.
R: The total number of runs scored by the player.
H: The total number of hits recorded by the player.
2B: The total number of doubles hit by the player.
3B: The total number of triples hit by the player.
HR: The total number of home runs hit by the player.
RBI: The total number of runs batted in (RBIs) by the player.*

In [43]:
import pandas as pd

In [44]:
df = pd.read_csv(r"C:\Users\fymatamton\Downloads\datasetss\500hits.csv", encoding = 'latin-1')

In [45]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [46]:
df.tail()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
460,Jim Wynn,15,1920,6653,1105,1665,285,39,291,964,1224,1427,225,101,0.250,0
461,Jorge Posada,17,1829,6092,900,1664,379,10,275,1065,936,1453,20,21,0.273,0
462,Brady Anderson,15,1834,6499,1062,1661,338,67,210,761,960,1190,315,100,0.256,0
463,Cookie Rojas,16,1822,6309,714,1660,254,25,54,593,396,489,74,68,0.263,0
464,Mickey Rivers,15,1468,5629,785,1660,247,71,61,499,266,471,267,90,0.295,0

In [47]:
df.shape

(465, 16)

In [48]:
df.describe()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
count,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.00000,465.000000,465.000000,465.000000,465.000000,465.000000
mean,17.049462,2048.698925,7511.455914,1150.313978,2170.247312,380.952688,78.554839,201.049462,894.260215,783.56129,847.470968,195.905376,58.083871,0.288712,0.329032
std,2.765186,354.391805,1294.065992,289.635071,424.190773,96.483460,49.363030,143.622664,486.193456,327.43195,489.224289,181.845543,48.027509,0.021208,0.474928
min,11.000000,1331.000000,4981.000000,601.000000,1660.000000,177.000000,3.000000,9.000000,0.000000,239.00000,0.000000,7.000000,0.000000,0.246000,0.000000
25%,15.000000,1802.000000,6523.000000,936.000000,1838.000000,312.000000,41.000000,79.000000,640.000000,535.00000,436.000000,63.000000,22.000000,0.273000,0.000000
50%,17.000000,1993.000000,7241.000000,1104.000000,2076.000000,366.000000,67.000000,178.000000,968.000000,736.00000,825.000000,137.000000,52.000000,0.287000,0.000000
75%,19.000000,2247.000000,8180.000000,1296.000000,2375.000000,436.000000,107.000000,292.000000,1206.000000,955.00000,1226.000000,285.000000,84.000000,0.300000,1.000000
max,26.000000,3308.000000,12364.000000,2295.000000,4189.000000,792.000000,309.000000,755.000000,2297.000000,2190.00000,2597.000000,1406.000000,335.000000,0.366000,2.000000

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PLAYER  465 non-null    object
 1   YRS     465 non-null    int64
 2   G       465 non-null    int64
 3   AB      465 non-null    int64
 4   R       465 non-null    int64
 5   H       465 non-null    int64
 6   2B      465 non-null    int64
 7   3B      465 non-null    int64
 8   HR      465 non-null    int64
 9   RBI     465 non-null    int64
 10  BB      465 non-null    int64
 11  SO      465 non-null    int64
 12  SB      465 non-null    int64
 13  CS      465 non-null    int64
 14  BA      465 non-null    float64
 15  HOF     465 non-null    int64
dtypes: float64(1), int64(14), object(1)
memory usage: 58.3+ KB

In [50]:
df = df.drop(columns = ['PLAYER', 'CS'])

In [51]:
x =df.iloc[:, 0:13]

In [52]:
y = df.iloc[:, 13]

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=17, test_size = 0.2)

In [55]:
x_train.shape

(372, 13)

In [56]:
x_test.shape

(93, 13)

In [57]:
y_train.shape

(372,)

In [58]:
y_test.shape

(93,)

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
dtc = DecisionTreeClassifier()#object creation

In [61]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [62]:
#Traning
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [63]:
#prediction
y_pred = dtc.predict(x_test)

In [68]:
from sklearn.metrics import confusion_matrix

In [69]:
print(confusion_matrix(y_test,y_pred)) #prints True-positive, T-N, F-P, F-N

[[51 10]
 [12 20]]

In [70]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.84      0.82        61
           1       0.67      0.62      0.65        32

    accuracy                           0.76        93
   macro avg       0.74      0.73      0.73        93
weighted avg       0.76      0.76      0.76        93

In [71]:
dtc.feature_importances_

array([0.02525798, 0.03355581, 0.03870641, 0.04215344, 0.38574252,
       0.04489872, 0.06034378, 0.02042228, 0.08416125, 0.08772083,
       0.04036804, 0.04028438, 0.09638455])

In [72]:
x.columns

Index(['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'BA'],
      dtype='object')

In [74]:
features=pd.DataFrame(dtc.feature_importances_, index = x.columns)

In [75]:
features.head(15)

            0
YRS  0.025258
G    0.033556
AB   0.038706
R    0.042153
H    0.385743
2B   0.044899
3B   0.060344
HR   0.020422
RBI  0.084161
BB   0.087721
SO   0.040368
SB   0.040284
BA   0.096385

In [77]:
dtc2 = DecisionTreeClassifier(criterion = 'entropy', ccp_alpha = 0.04)

In [78]:
dtc2.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.04, criterion='entropy')

In [79]:
#predictions
y_pred2 = dtc2.predict(x_test)
print(confusion_matrix(y_test, y_pred2))

[[50 11]
 [ 9 23]]

In [80]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83        61
           1       0.68      0.72      0.70        32

    accuracy                           0.78        93
   macro avg       0.76      0.77      0.77        93
weighted avg       0.79      0.78      0.79        93

In [84]:
features2 = pd.DataFrame(dtc2.feature_importances_, index = x.columns)
features2.head(15)

            0
YRS  0.000000
G    0.000000
AB   0.000000
R    0.000000
H    0.837977
2B   0.000000
3B   0.000000
HR   0.000000
RBI  0.000000
BB   0.000000
SO   0.000000
SB   0.000000
BA   0.162023

In [87]:
#checking accuracy
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy is:", accuracy_score(y_test, y_pred2)*100)

Accuracy is: 78.49462365591397